<?php
$movies = [
  [
      'title' => 'Inception',
      'year' => 2010,
      'genre' => ['Action', 'Sci-Fi'],
      'description' => 'A thief who enters the dreams of others to steal their secrets.',
      'duration' => 148,
  ],
  [
      'title' => 'The Shawshank Redemption',
      'year' => 1994,
      'genre' => ['Drama'],
      'description' => 'Two imprisoned men bond over a number of years, finding solace and eventual redemption through acts of common decency.',
      'duration' => 142,
  ],
  [
      'title' => 'The Dark Knight',
      'year' => 2008,
      'genre' => ['Action', 'Crime', 'Drama'],
      'description' => 'When the menace known as The Joker emerges, Batman must confront his greatest psychological and physical challenge.',
      'duration' => 152,
  ],
  [
    'title' => 'The Matrix',
    'year' => 1999,
    'genre' => ['Action', 'Sci-Fi'],
    'description' => 'A computer hacker learns about the true nature of his reality and his role in the war against its controllers.',
    'duration' => 136,
],
[
    'title' => 'Pulp Fiction',
    'year' => 1994,
    'genre' => ['Crime', 'Drama'],
    'description' => 'The lives of two mob hitmen, a boxer, a gangster and his wife, and a pair of diner bandits intertwine in four tales of violence and redemption.',
    'duration' => 154,
],
[
    'title' => 'Forrest Gump',
    'year' => 1994,
    'genre' => ['Drama', 'Romance'],
    'description' => 'The presidencies of Kennedy through Clinton are seen through the eyes of a mentally disabled man.',
    'duration' => 142,
],
[
    'title' => 'The Godfather',
    'year' => 1972,
    'genre' => ['Crime', 'Drama'],
    'description' => 'The aging patriarch of an organized crime dynasty transfers control of his clandestine empire to his reluctant son.',
    'duration' => 175,
],
[
    'title' => 'Jurassic Park',
    'year' => 1993,
    'genre' => ['Adventure', 'Sci-Fi'],
    'description' => 'A pragmatic paleontologist visiting an almost complete theme park is tasked with protecting a couple of kids after a power failure causes the park\'s cloned dinosaurs to run loose.',
    'duration' => 127,
],
[
    'title' => 'The Silence of the Lambs',
    'year' => 1991,
    'genre' => ['Crime', 'Drama', 'Thriller'],
    'description' => 'A young FBI cadet must receive the help of an incarcerated and manipulative cannibal killer to help catch another serial killer, a madman who skins his victims.',
    'duration' => 118,
],
[
    'title' => 'Inglourious Basterds',
    'year' => 2009,
    'genre' => ['Adventure', 'Drama', 'War'],
    'description' => 'In Nazi-occupied France during World War II, a plan to assassinate Nazi leaders by a group of Jewish U.S. soldiers coincides with a theatre owner\'s vengeful plans for the same.',
    'duration' => 153,
],
[
    'title' => 'The Shining',
    'year' => 1980,
    'genre' => ['Drama', 'Horror'],
    'description' => 'A family heads to an isolated hotel for the winter where a sinister presence influences the father into violence, while his psychic son sees horrific forebodings from both past and future.',
    'duration' => 146,
],
[
    'title' => 'Back to the Future',
    'year' => 1985,
    'genre' => ['Adventure', 'Comedy', 'Sci-Fi'],
    'description' => 'Marty McFly, a 17-year-old high school student, is accidentally sent 30 years into the past in a time-traveling DeLorean invented by his close friend, eccentric scientist Doc Brown.',
    'duration' => 116,
],
];